# Кросс-валидация

In [9]:
from sklearn import datasets
from sklearn import model_selection
import numpy as np

In [10]:
iris = datasets.load_iris()
train_data, test_data, train_labels, test_labels = model_selection.train_test_split(
    iris.data, iris.target, test_size=0.3
)

In [11]:
print('Размер обучающей выборки {} объектов \n Размер тестовой выборки {} объектов'.format(len(train_data), len(test_data)))

Размер обучающей выборки 105 объектов 
 Размер тестовой выборки 45 объектов


## Стратегии проведения кросс-валидации

### KFold
Каждая выборка разбивается на k блоков каждый блок k-1 раз участвует в обучении и 1 раз в тестировании
##### Shuffle=True перемешивает выборку
#### Random_state = int Фиксирует случайность перемешивания выборки

In [12]:
cross_valid = model_selection.KFold(2, shuffle=True, random_state=1)
cross_valid.get_n_splits(iris.data, iris.target)
for train_cross, test_cross in cross_valid.split(iris.data, iris.target):
    print('TRAIN:', iris.data[train_cross], 'TRAIN TARGET', iris.target[test_cross])
    print('TEST:', iris.data[test_cross], 'TEST TARGET:', iris.target[test_cross])

TRAIN: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [5.7 4.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [4.8 3.1 1.6 0.2]
 [5.2 4.1 1.5 0.1]
 [4.9 3.1 1.5 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [5.  3.5 1.6 0.6]
 [4.6 3.2 1.4 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.9 3.1 4.9 1.5]
 [4.9 2.4 3.3 1. ]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.4 2.9 4.3 1.3]
 [6.8 2.8 4.8 1.4]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.  2.3 3.3 1. ]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [6.3

### StratifiedKFold
Сохраняется соотношение классов в обучающей и тестовой выборке

### ShuffleSplit
Строит случайные перестановки
n_iter = количество разных блоков

In [13]:
shuffle_valid = model_selection.ShuffleSplit(n_splits=50, test_size=0.2)
shuffle_valid.get_n_splits(iris.data, iris.target)
for train_cross, test_cross in shuffle_valid.split(iris.data, iris.target):
    print('TRAIN DATA:')
    print(iris.data[test_cross])
    print('TRAIN TARGET:')
    print(iris.target[test_cross])
    print('TEST DATA:')
    print(iris.data[test_cross])
    print('TEST TARGET:')
    print(iris.target[test_cross])

TRAIN DATA:
[[5.  3.3 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [5.7 3.8 1.7 0.3]
 [5.6 2.9 3.6 1.3]
 [5.  3.  1.6 0.2]
 [7.2 3.6 6.1 2.5]
 [6.5 3.  5.8 2.2]
 [4.8 3.  1.4 0.3]
 [6.5 2.8 4.6 1.5]
 [4.7 3.2 1.3 0.2]
 [5.8 2.7 5.1 1.9]
 [4.9 3.  1.4 0.2]
 [5.7 3.  4.2 1.2]
 [4.7 3.2 1.6 0.2]
 [5.  3.4 1.5 0.2]
 [4.4 3.  1.3 0.2]
 [5.1 3.3 1.7 0.5]
 [5.5 4.2 1.4 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.4 1.4 0.3]
 [6.9 3.1 5.1 2.3]
 [6.4 3.1 5.5 1.8]
 [6.5 3.  5.5 1.8]
 [5.4 3.  4.5 1.5]
 [6.5 3.  5.2 2. ]
 [7.2 3.  5.8 1.6]
 [7.  3.2 4.7 1.4]
 [6.7 3.3 5.7 2.5]
 [5.  2.  3.5 1. ]
 [6.  2.2 4.  1. ]]
TRAIN TARGET:
[0 0 0 1 0 2 2 0 1 0 2 0 1 0 0 0 0 0 0 0 2 2 2 1 2 2 1 2 1 1]
TEST DATA:
[[5.  3.3 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [5.7 3.8 1.7 0.3]
 [5.6 2.9 3.6 1.3]
 [5.  3.  1.6 0.2]
 [7.2 3.6 6.1 2.5]
 [6.5 3.  5.8 2.2]
 [4.8 3.  1.4 0.3]
 [6.5 2.8 4.6 1.5]
 [4.7 3.2 1.3 0.2]
 [5.8 2.7 5.1 1.9]
 [4.9 3.  1.4 0.2]
 [5.7 3.  4.2 1.2]
 [4.7 3.2 1.6 0.2]
 [5.  3.4 1.5 0.2]
 [4.4 3.  1.3 0.2]
 [5.1 3.3 1.7 0.5]
 [5.5 4

### LeaveOneOut

Каждый объект побудет в выборке по одному разу